
begin
	DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA;
	DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;
	DBMS_RESOURCE_MANAGER.DELETE_PLAN_CASCADE ( 'restrictive_plan' );
	DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
	DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;
end;
/

